"""credential_and_usage_index_cleanup

Revision ID: bca2a7b69d22
Revises: 20260327_04
Create Date: 2026-03-28 15:03:44.030318
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'bca2a7b69d22'
down_revision = '20260327_04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_credentials_provider_auth_kind_state'), table_name='provider_credentials')
    op.create_index(op.f('ix_provider_credentials_auth_kind'), 'provider_credentials', ['auth_kind'], unique=False)
    op.create_index(op.f('ix_provider_credentials_provider'), 'provider_credentials', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_credentials_state'), 'provider_credentials', ['state'], unique=False)
    op.drop_index(op.f('ix_usage_events_created_at'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_principal_id_status'), table_name='usage_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usage_events_principal_id_status'), 'usage_events', ['principal_id', 'status'], unique=False)
    op.create_index(op.f('ix_usage_events_created_at'), 'usage_events', ['created_at'], unique=False)
    op.drop_index(op.f('ix_provider_credentials_state'), table_name='provider_credentials')
    op.drop_index(op.f('ix_provider_credentials_provider'), table_name='provider_credentials')
    op.drop_index(op.f('ix_provider_credentials_auth_kind'), table_name='provider_credentials')
    op.create_index(op.f('ix_provider_credentials_provider_auth_kind_state'), 'provider_credentials', ['provider', 'auth_kind', 'state'], unique=False)
    # ### end Alembic commands ###
