apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "enterprise-llm-proxy.fullname" . }}
  labels:
    {{- include "enterprise-llm-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    {{- if .Values.router.redirectToBaseUrl }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-router-int-to-public@kubernetescrd" .Release.Namespace | quote }}
    {{- end }}
    {{- if .Values.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.tls.clusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName | quote }}
  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ if and .Values.gateway.enabled .Values.gateway.routePrimaryIngress }}{{ include "enterprise-llm-proxy.fullname" . }}-gateway{{ else }}{{ default (include "enterprise-llm-proxy.fullname" .) .Values.router.backendServiceName }}{{ end }}
                port:
                  number: {{ if and .Values.gateway.enabled .Values.gateway.routePrimaryIngress }}{{ .Values.gateway.service.port }}{{ else }}{{ .Values.service.port }}{{ end }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.hostname | quote }}
      secretName: {{ .Values.tls.secretName | quote }}
  {{- end }}
